SELECT USER
FROM DUAL;
--==>> SCOTT

-- 테이블 생성
CREATE TABLE TBL_STUDENT
( SID   NUMBER
, NAME  VARCHAR2(30)
, TEL   VARCHAR2(40)
, CONSTRAINT STUDENT_SID_PK PRIMARY KEY(SID)
);
--==>> Table TBL_STUDENT이(가) 생성되었습니다.


-- 데이터 입력
INSERT INTO TBL_STUDENT(SID, NAME, TEL)
VALUES(1, '최나윤', '010-1111-1111');

INSERT INTO TBL_STUDENT(SID, NAME, TEL)
VALUES(2, '박원석', '010-2222-2222');


INSERT INTO TBL_STUDENT(SID, NAME, TEL)
VALUES(3, '한은영', '010-3333-3333');


INSERT INTO TBL_STUDENT(SID, NAME, TEL)
VALUES(4, '조현하', '010-4444-4444');
--==>> 1 행 이(가) 삽입되었습니다. * 4


-- 확인
SELECT *
FROM TBL_STUDENT;



-- 테이블 생성
CREATE TABLE TBL_GRADE
( SID   NUMBER
, SUB1  NUMBER(3)
, SUB2  NUMBER(3)
, SUB3  NUMBER(3)
, CONSTRAINT GRADE_SID_PK PRIMARY KEY(SID)
, CONSTRAINT GRADE_SID_FK FOREIGN KEY(SID)
            REFERENCES TBL_STUDENT(SID)
, CONSTRAINT GREDE_SUB1_CK CHECK(SUB1 BETWEEN 0 AND 100)
, CONSTRAINT GREDE_SUB2_CK CHECK(SUB2 BETWEEN 0 AND 100)
, CONSTRAINT GREDE_SUB3_CK CHECK(SUB3 BETWEEN 0 AND 100)
);
--==>> Table TBL_GRADE이(가) 생성되었습니다.

-- 데이터 입력
INSERT INTO TBL_GRADE(SID, SUB1, SUB2, SUB3)
VALUES(1, 90, 80, 70);

INSERT INTO TBL_GRADE(SID, SUB1, SUB2, SUB3)
VALUES(2, 70, 60, 50);

INSERT INTO TBL_GRADE(SID, SUB1, SUB2, SUB3)
VALUES(3, 50, 40, 30);

INSERT INTO TBL_GRADE(SID, SUB1, SUB2, SUB3)
VALUES(4, 90, 90, 30);
--==>> 1 행 이(가) 삽입되었습니다. * 4

SELECT *
FROM TBL_STUDENT;

SELECT *
FROM TBL_GRADE;


-- 커밋
COMMIT;


-- 뷰 생성(STUDENTVIEW)
CREATE OR REPLACE VIEW STUDENTVIEW
AS
SELECT SID, NAME, TEL, (SELECT COUNT(*) FROM TBL_GRADE WHERE SID = S.SID) AS SUB
FROM TBL_STUDENT S;
--==>> View STUDENTVIEW이(가) 생성되었습니다.

-- 뷰 생성(GRADEVIEW)
CREATE OR REPLACE VIEW GRADEVIEW
AS
SELECT S.SID AS SID
     , S.NAME AS NAME
     , S.TEL AS TEL
     ,G.SUB1 AS SUB1
     ,G.SUB2 AS SUB2
     , G.SUB3 AS SUB3
     , (G.SUB1 + G.SUB2 + G.SUB3) AS TOT
     ,(G.SUB1 + G.SUB2 + G.SUB3)/3 AS AVG
     , (CASE WHEN (G.SUB1 + G.SUB2 + G.SUB3)/3 < 60 THEN '불합격'
             WHEN (G.SUB1 <= 40) OR (G.SUB2 <= 40) OR (G.SUB3 <= 40) THEN '과락'
             ELSE '합격'
             END) AS CH
FROM TBL_STUDENT S JOIN TBL_GRADE G
ON S.SID = G.SID;
--==>> View GRADEVIEW이(가) 생성되었습니다.



SELECT SID, NAME, TEL, SUB
FROM STUDENTVIEW;

SELECT SID, NAME, SUB1, SUB2, SUB3, TOT, AVG, CH
FROM GRADEVIEW;
/*
1	최나윤	90	80	70	240	80	합격
2	박원석	70	60	50	180	60	합격
3	한은영	50	40	30	120	40	불합격
4	조현하	90	90	30	210	70	과락
*/


--인원 수 확인
SELECT COUNT(*) AS COUNT
FROM TBL_STUDENT;
--==>> 4


SELECT *
FROM TBL_STUDENT;

COMMIT;

SELECT *
FROM TBL_STUDENT
ORDER BY SID;
